
env_files = [
  "./.env"
]

[env]

[tasks.test-script]
script = '''
echo ${MASTER_ADDR}
echo args: ${@}
'''

[tasks.cluster_info]
command = "kubectl"
args = ["cluster-info"]


[tasks.sbt-package]
script = [
  "cd ..",
  "sbt package"
]

[tasks.sbt-assembly]
script = [
  "cd ..",
  "sbt assembly"
]

# cargo make --makefile dev.toml send-app
[tasks.send-app]
command = "scp"
args = [
  "-rp",
  "${APP_DIR}",
  "${SHARE_ADDR}"
]
dependencies = ["sbt-package"]

# cargo make --makefile dev.toml send-conf
[tasks.send-conf]
command = "scp"
args = [
  "-rp",
  "${CONF_DIR}",
  "${SHARE_ADDR}"
]

# cargo make --makefile dev.toml send-deps
[tasks.send-deps]
command = "scp"
args = [
  "-rp",
  "${DEPS_DIR}",
  "${SHARE_ADDR}"
]

# cargo make -e JOB_NAME=transfer-test -e CLASS_NAME=jotting.task.SaveProductValuation --makefile dev.toml daily_raw_data_transfer
[tasks.daily_raw_data_transfer]
script = '''
kubectl run \
  --namespace ${K8S_NAMESPACE} ${JOB_NAME} \
  --rm \
  --tty -i \
  --restart Never \
  --image ${K8S_CONTAINER_IMAGE} \
  -- \
  spark-submit \
  --master ${SPARK_ADDR} \
  --deploy-mode cluster \
  --files ${SHARE_FILES} \
  --packages com.typesafe:config:1.4.2 \
  --jars ${SHARE_JARS_MYSQL},${SHARE_JARS_POSTGRES} \
  --class ${CLASS_NAME} \
  ${SHARE_APP}
'''

[tasks.job3]
script = '''
kubectl run \
  --namespace ${K8S_NAMESPACE} job3 \
  --rm \
  --tty -i \
  --restart Never \
  --image ${K8S_CONTAINER_IMAGE} \
  -- \
  spark-submit \
  --master ${SPARK_ADDR} \
  --deploy-mode cluster \
  --files ${SHARE_FILES} \
  --packages com.typesafe:config:1.4.2 \
  --jars ${SHARE_JARS_POSTGRES} \
  --class jotting.simple.Job3 \
  ${SHARE_APP} ${@}
'''
